name: Makefile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@master
    - name: Install deps
      run: sudo apt-get -y install libasound2-dev
    - name: make
      run: make
